services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    volumes: []
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DEBUG: "False"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    volumes: []

  nginx:
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
