apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: web-template
data:
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DEBUG: "False"
  DB_NAME: "website_template"
  DB_USER: "postgres"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  ALLOWED_HOSTS: "app.example.com"
